// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t *ui_Screen2;
void ui_event_Chinese(lv_event_t *e);
lv_obj_t *ui_Chinese;
void ui_event_Thai(lv_event_t *e);
lv_obj_t *ui_Thai;
void ui_event_English(lv_event_t *e);
lv_obj_t *ui_English;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label3;

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_LeftPanel;
lv_obj_t *ui_LeftTranscribe2;
lv_obj_t *ui_LeftTranscribeBubble2;
lv_obj_t *ui_LeftTranscribeText2;
lv_obj_t *ui_LeftTranslate;
lv_obj_t *ui_LeftTranslateBubble1;
lv_obj_t *ui_LeftTranslateText1;
lv_obj_t *ui_LeftTranscribe1;
lv_obj_t *ui_LeftTranscribeBubble1;
lv_obj_t *ui_LeftTranscribeText1;
lv_obj_t *ui_RightPanel;
lv_obj_t *ui_RightTranscribe;
lv_obj_t *ui_RightTranscribeBubble;
lv_obj_t *ui_RightTranscribeText;
lv_obj_t *ui_RightTranslate;
lv_obj_t *ui_RightTranslateBubble;
lv_obj_t *ui_RightTranslateText;
lv_obj_t *ui_RightTranscribe1;
lv_obj_t *ui_RightTranscribeBubble1;
lv_obj_t *ui_RightTranscribeText1;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Image1;
lv_obj_t *ui____initial_actions0;
lv_font_t *selected_font;
///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Chinese(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        selected_font = &ui_font_Chinese;
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Thai(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        selected_font = &ui_font_Thai;
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_English(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        selected_font = &ui_font_English;
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen2_screen_init();
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen2);
}
