// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_LeftPanel;
extern lv_obj_t * ui_LeftTranscribe;
extern lv_obj_t * ui_LeftTranscribeBubble;
extern lv_obj_t * ui_LeftTranscribeText;
extern lv_obj_t * ui_LeftTranslate;
extern lv_obj_t * ui_LeftTranslateBubble1;
extern lv_obj_t * ui_LeftTranslateText1;
extern lv_obj_t * ui_LeftTranscribe1;
extern lv_obj_t * ui_LeftTranscribeBubble1;
extern lv_obj_t * ui_LeftTranscribeText1;
extern lv_obj_t * ui_RightPanel;
extern lv_obj_t * ui_RightTranscribe;
extern lv_obj_t * ui_RightTranscribeBubble;
extern lv_obj_t * ui_RightTranscribeText;
extern lv_obj_t * ui_RightTranslate;
extern lv_obj_t * ui_RightTranslateBubble;
extern lv_obj_t * ui_RightTranslateText;
extern lv_obj_t * ui_RightTranscribe1;
extern lv_obj_t * ui_RightTranscribeBubble1;
extern lv_obj_t * ui_RightTranscribeText1;
extern lv_obj_t * ui____initial_actions0;





LV_FONT_DECLARE(ui_font_Chinese);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
