// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

    // SCREEN: ui_Start_Screen
    void ui_Start_Screen_screen_init(void);
    extern lv_obj_t *ui_Start_Screen;
    extern lv_obj_t *ui_Panel_User_1;
    extern lv_obj_t *ui_English_Button;
    extern lv_obj_t *ui_Label4;
    extern lv_obj_t *ui_Chinese_Button;
    extern lv_obj_t *ui_Label5;
    extern lv_obj_t *ui_Thai_Button;
    extern lv_obj_t *ui_Label6;
    extern lv_obj_t *ui_Bahasa_Melayu_Button;
    extern lv_obj_t *ui_Label7;
    extern lv_obj_t *ui_Bahasa_Indonesia_Button;
    extern lv_obj_t *ui_Label8;
    extern lv_obj_t *ui_Vietnamese_Button;
    extern lv_obj_t *ui_Label9;
    extern lv_obj_t *ui_Hindi_Button;
    extern lv_obj_t *ui_Label10;
    extern lv_obj_t *ui_Filipino_Button;
    extern lv_obj_t *ui_Label11;
    extern lv_obj_t *ui_Spacer_Bar_White;
    extern lv_obj_t *ui_Optional_Text;
    extern lv_obj_t *ui_Panel_User_2;
    extern lv_obj_t *ui_English_Button1;
    extern lv_obj_t *ui_Label2;
    extern lv_obj_t *ui_Chinese_Button1;
    extern lv_obj_t *ui_Label3;
    extern lv_obj_t *ui_Thai_Button1;
    extern lv_obj_t *ui_Label12;
    extern lv_obj_t *ui_Bahasa_Melayu_Button1;
    extern lv_obj_t *ui_Label13;
    extern lv_obj_t *ui_Bahasa_Indonesia_Button1;
    extern lv_obj_t *ui_Label14;
    extern lv_obj_t *ui_Vietnamese_Button1;
    extern lv_obj_t *ui_Label15;
    extern lv_obj_t *ui_Hindi_Button1;
    extern lv_obj_t *ui_Label16;
    extern lv_obj_t *ui_Filipino_Button1;
    extern lv_obj_t *ui_Label17;
    // SCREEN: ui_Start_Screen_v2
    void ui_Start_Screen_v2_screen_init(void);
    extern lv_obj_t *ui_Start_Screen_v2;
    extern lv_obj_t *ui_Panel_User_5;
    extern lv_obj_t *ui_Selected_Bubble;
    void ui_event_English_Button4(lv_event_t *e);
    extern lv_obj_t *ui_English_Button4;
    extern lv_obj_t *ui_Label1;
    void ui_event_Chinese_Button4(lv_event_t *e);
    extern lv_obj_t *ui_Chinese_Button4;
    extern lv_obj_t *ui_Label35;
    void ui_event_Thai_Button4(lv_event_t *e);
    extern lv_obj_t *ui_Thai_Button4;
    extern lv_obj_t *ui_Label36;
    void ui_event_Bahasa_Melayu_Button4(lv_event_t *e);
    extern lv_obj_t *ui_Bahasa_Melayu_Button4;
    extern lv_obj_t *ui_Label37;
    void ui_event_Bahasa_Indonesia_Button4(lv_event_t *e);
    extern lv_obj_t *ui_Bahasa_Indonesia_Button4;
    extern lv_obj_t *ui_Label38;
    void ui_event_Vietnamese_Button4(lv_event_t *e);
    extern lv_obj_t *ui_Vietnamese_Button4;
    extern lv_obj_t *ui_Label39;
    void ui_event_Hindi_Button4(lv_event_t *e);
    extern lv_obj_t *ui_Hindi_Button4;
    extern lv_obj_t *ui_Label40;
    void ui_event_Filipino_Button4(lv_event_t *e);
    extern lv_obj_t *ui_Filipino_Button4;
    extern lv_obj_t *ui_Label41;
    extern lv_obj_t *ui_Spacer_Bar_White2;
    extern lv_obj_t *ui_Optional_Text1;
    extern lv_obj_t *ui_language_icon1;
    extern lv_obj_t *ui_Panel_User_6;
    void ui_event_English_Button5(lv_event_t *e);
    extern lv_obj_t *ui_English_Button5;
    extern lv_obj_t *ui_Label42;
    void ui_event_Chinese_Button5(lv_event_t *e);
    extern lv_obj_t *ui_Chinese_Button5;
    extern lv_obj_t *ui_Label43;
    void ui_event_Thai_Button5(lv_event_t *e);
    extern lv_obj_t *ui_Thai_Button5;
    extern lv_obj_t *ui_Label44;
    void ui_event_Bahasa_Melayu_Button5(lv_event_t *e);
    extern lv_obj_t *ui_Bahasa_Melayu_Button5;
    extern lv_obj_t *ui_Label45;
    void ui_event_Bahasa_Indonesia_Button5(lv_event_t *e);
    extern lv_obj_t *ui_Bahasa_Indonesia_Button5;
    extern lv_obj_t *ui_Label46;
    void ui_event_Vietnamese_Button5(lv_event_t *e);
    extern lv_obj_t *ui_Vietnamese_Button5;
    extern lv_obj_t *ui_Label47;
    void ui_event_Hindi_Button5(lv_event_t *e);
    extern lv_obj_t *ui_Hindi_Button5;
    extern lv_obj_t *ui_Label48;
    void ui_event_Filipino_Button5(lv_event_t *e);
    extern lv_obj_t *ui_Filipino_Button5;
    extern lv_obj_t *ui_Label49;
    // SCREEN: ui_Translation_Screen
    void ui_Translation_Screen_screen_init(void);
    extern lv_obj_t *ui_Translation_Screen;
    extern lv_obj_t *ui_Dialogue_User_1;
    extern lv_obj_t *ui_Type_C_Panel_2;
    extern lv_obj_t *ui_Type_C_Bubble_2;
    extern lv_obj_t *ui_Type_C_Text_2;
    extern lv_obj_t *ui_Type_C_Panel;
    extern lv_obj_t *ui_Type_C_Bubble;
    extern lv_obj_t *ui_Type_C_Text;
    extern lv_obj_t *ui_Type_A_Panel;
    extern lv_obj_t *ui_Type_A_Bubble;
    extern lv_obj_t *ui_Type_A_Text;
    extern lv_obj_t *ui_Type_B_Panel;
    extern lv_obj_t *ui_Type_B_Bubble;
    extern lv_obj_t *ui_Type_B_Text;
    extern lv_obj_t *ui_Status_Panel;
    extern lv_obj_t *ui_Icon_Mic;
    extern lv_obj_t *ui_Icon_Mic_Inactive;
    extern lv_obj_t *ui_Icon_Mic_Active;
    extern lv_obj_t *ui_Dialogue_User_2;
    extern lv_obj_t *ui_Type_A_Panel_2;
    extern lv_obj_t *ui_Type_A_Bubble_2;
    extern lv_obj_t *ui_Type_A_Text_2;
    extern lv_obj_t *ui_Type_A_Panel_3;
    extern lv_obj_t *ui_Type_A_Bubble_3;
    extern lv_obj_t *ui_Type_A_Text_3;
    extern lv_obj_t *ui_Type_C_Panel_3;
    extern lv_obj_t *ui_Type_C_Bubble_3;
    extern lv_obj_t *ui_Type_C_Text_3;
    extern lv_obj_t *ui_Type_D_Panel;
    extern lv_obj_t *ui_Type_D_Bubble;
    extern lv_obj_t *ui_Type_D_Text;
    // SCREEN: ui_Loading_Screen
    void ui_Loading_Screen_screen_init(void);
    extern lv_obj_t *ui_Loading_Screen;
    extern lv_obj_t *ui_KLASSES_Logo;
    extern lv_obj_t *ui_Spinner1;
    // SCREEN: ui_Translation_Screen_v2
    void ui_Translation_Screen_v2_screen_init(void);
    extern lv_obj_t *ui_Translation_Screen_v2;
    extern lv_obj_t *ui_Dialogue_User_3;
    extern lv_obj_t *ui_Type_C_Panel_1;
    extern lv_obj_t *ui_Type_C_Bubble_1;
    extern lv_obj_t *ui_Type_C_Text_1;
    extern lv_obj_t *ui_Type_C_Panel1;
    extern lv_obj_t *ui_Type_C_Bubble1;
    extern lv_obj_t *ui_Type_C_Text1;
    extern lv_obj_t *ui_Type_A_Panel1;
    extern lv_obj_t *ui_Type_A_Bubble1;
    extern lv_obj_t *ui_Type_A_Text1;
    extern lv_obj_t *ui_Type_B_Panel1;
    extern lv_obj_t *ui_Type_B_Bubble1;
    extern lv_obj_t *ui_Type_B_Text1;
    extern lv_obj_t *ui_Status_Panel1;
    extern lv_obj_t *ui_Icon_Mic1;
    extern lv_obj_t *ui_Icon_Mic_Inactive1;
    extern lv_obj_t *ui_Icon_Mic_Active1;
    extern lv_obj_t *ui_Dialogue_User_4;
    extern lv_obj_t *ui_Type_A_Panel_1;
    extern lv_obj_t *ui_Type_A_Bubble_1;
    extern lv_obj_t *ui_Type_A_Text_1;
    extern lv_obj_t *ui_Type_A_Panel_4;
    extern lv_obj_t *ui_Type_A_Bubble_4;
    extern lv_obj_t *ui_Type_A_Text_4;
    extern lv_obj_t *ui_Type_C_Panel_4;
    extern lv_obj_t *ui_Type_C_Bubble_4;
    extern lv_obj_t *ui_Type_C_Text_4;
    extern lv_obj_t *ui_Type_D_Panel1;
    extern lv_obj_t *ui_Type_D_Bubble1;
    extern lv_obj_t *ui_Type_D_Text1;
    extern lv_obj_t *ui____initial_actions0;

    extern const lv_font_t *selected_font_1;
    extern const lv_font_t *selected_font_2;
    extern bool lang_selected_1;
    extern bool lang_selected_2;
    extern uint8_t selected_lang_1;
    extern uint8_t selected_lang_2;

    LV_IMG_DECLARE(ui_img_mic_icon_png);          // assets/mic icon.png
    LV_IMG_DECLARE(ui_img_mic_icon_inactive_png); // assets/Mic Icon Inactive.png
    LV_IMG_DECLARE(ui_img_mic_icon_active_png);   // assets/Mic Icon Active.png
    LV_IMG_DECLARE(ui_img_1221162986);            // assets/KLASSES Logo (recreated) 1024x1024.png
    LV_IMG_DECLARE(ui_img_globe_grey_png);        // assets/globe_grey.png

    LV_FONT_DECLARE(ui_font_Noto_Sans_Regular);
    LV_FONT_DECLARE(ui_font_Noto_Sans_Regular_Devanagari);
    LV_FONT_DECLARE(ui_font_Noto_Sans_Regular_SC);
    LV_FONT_DECLARE(ui_font_Noto_Sans_Regular_Thai_Looped);

    void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
