// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Loading_Screen_screen_init(void)
{
    ui_Loading_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Loading_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Loading_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Loading_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KLASSES_Logo = lv_img_create(ui_Loading_Screen);
    lv_img_set_src(ui_KLASSES_Logo, &ui_img_1221162986);
    lv_obj_set_width(ui_KLASSES_Logo, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_KLASSES_Logo, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_align(ui_KLASSES_Logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KLASSES_Logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_KLASSES_Logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_KLASSES_Logo, 100);

    ui_Spinner1 = lv_spinner_create(ui_Loading_Screen, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 140);
    lv_obj_set_height(ui_Spinner1, 140);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x144A82), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Spinner1, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

}
