// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Chinese = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Chinese, 100);
    lv_obj_set_height(ui_Chinese, 50);
    lv_obj_set_x(ui_Chinese, -162);
    lv_obj_set_y(ui_Chinese, -79);
    lv_obj_set_align(ui_Chinese, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chinese, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Chinese, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Thai = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Thai, 100);
    lv_obj_set_height(ui_Thai, 50);
    lv_obj_set_x(ui_Thai, 0);
    lv_obj_set_y(ui_Thai, -83);
    lv_obj_set_align(ui_Thai, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Thai, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Thai, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_English = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_English, 100);
    lv_obj_set_height(ui_English, 50);
    lv_obj_set_x(ui_English, 166);
    lv_obj_set_y(ui_English, -79);
    lv_obj_set_align(ui_English, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_English, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_English, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -164);
    lv_obj_set_y(ui_Label1, -78);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "CN");

    ui_Label2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -3);
    lv_obj_set_y(ui_Label2, -82);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "TH");

    ui_Label3 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 166);
    lv_obj_set_y(ui_Label3, -78);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "EN");

    lv_obj_add_event_cb(ui_Chinese, ui_event_Chinese, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Thai, ui_event_Thai, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_English, ui_event_English, LV_EVENT_ALL, NULL);

}
