// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LeftPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_LeftPanel, 425);
    lv_obj_set_height(ui_LeftPanel, 376);
    lv_obj_set_x(ui_LeftPanel, -228);
    lv_obj_set_y(ui_LeftPanel, -7);
    lv_obj_set_align(ui_LeftPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LeftPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LeftPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_LeftTranscribe = lv_obj_create(ui_LeftPanel);
    lv_obj_set_width(ui_LeftTranscribe, lv_pct(100));
    lv_obj_set_height(ui_LeftTranscribe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LeftTranscribe, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LeftTranscribe, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_pad_left(ui_LeftTranscribe, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LeftTranscribe, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LeftTranscribe, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LeftTranscribe, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LeftTranscribeBubble = lv_obj_create(ui_LeftTranscribe);
    lv_obj_set_width(ui_LeftTranscribeBubble, lv_pct(80));
    lv_obj_set_height(ui_LeftTranscribeBubble, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LeftTranscribeBubble, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_LeftTranscribeBubble, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LeftTranscribeBubble, lv_color_hex(0x64BDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LeftTranscribeBubble, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_LeftTranscribeBubble, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LeftTranscribeBubble, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LeftTranscribeBubble, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LeftTranscribeBubble, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LeftTranscribeText = lv_label_create(ui_LeftTranscribeBubble);
    lv_obj_set_width(ui_LeftTranscribeText, lv_pct(100));
    lv_obj_set_height(ui_LeftTranscribeText, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_LeftTranscribeText, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LeftTranscribeText,
                      "书、杂志等中区别于图片的）正文，文字材料, （移动电话或传呼机发送的）短消息");
    lv_obj_set_style_text_align(ui_LeftTranscribeText, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LeftTranscribeText, &ui_font_Chinese, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LeftTranscribeText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LeftTranscribeText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LeftTranscribeText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LeftTranscribeText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LeftTranslate = lv_obj_create(ui_LeftPanel);
    lv_obj_set_width(ui_LeftTranslate, lv_pct(100));
    lv_obj_set_height(ui_LeftTranslate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LeftTranslate, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LeftTranslate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_pad_left(ui_LeftTranslate, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LeftTranslate, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LeftTranslate, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LeftTranslate, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LeftTranslateBubble1 = lv_obj_create(ui_LeftTranslate);
    lv_obj_set_width(ui_LeftTranslateBubble1, lv_pct(80));
    lv_obj_set_height(ui_LeftTranslateBubble1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LeftTranslateBubble1, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_LeftTranslateBubble1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LeftTranslateBubble1, lv_color_hex(0x78868B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LeftTranslateBubble1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_LeftTranslateBubble1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LeftTranslateBubble1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LeftTranslateBubble1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LeftTranslateBubble1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LeftTranslateText1 = lv_label_create(ui_LeftTranslateBubble1);
    lv_obj_set_width(ui_LeftTranslateText1, lv_pct(100));
    lv_obj_set_height(ui_LeftTranslateText1, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_LeftTranslateText1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LeftTranslateText1,
                      "Text dsad asd asd sa asd as dsad  qwwq we rwqr we rwer ewr wq rewq ewq rwq rwq rqwe rwqe r");
    lv_obj_set_style_text_align(ui_LeftTranslateText1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LeftTranslateText1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LeftTranslateText1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LeftTranslateText1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LeftTranslateText1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LeftTranscribe1 = lv_obj_create(ui_LeftPanel);
    lv_obj_set_width(ui_LeftTranscribe1, lv_pct(100));
    lv_obj_set_height(ui_LeftTranscribe1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LeftTranscribe1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LeftTranscribe1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_pad_left(ui_LeftTranscribe1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LeftTranscribe1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LeftTranscribe1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LeftTranscribe1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LeftTranscribeBubble1 = lv_obj_create(ui_LeftTranscribe1);
    lv_obj_set_width(ui_LeftTranscribeBubble1, lv_pct(80));
    lv_obj_set_height(ui_LeftTranscribeBubble1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LeftTranscribeBubble1, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_LeftTranscribeBubble1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LeftTranscribeBubble1, lv_color_hex(0x64BDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LeftTranscribeBubble1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_LeftTranscribeBubble1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LeftTranscribeBubble1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LeftTranscribeBubble1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LeftTranscribeBubble1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LeftTranscribeText1 = lv_label_create(ui_LeftTranscribeBubble1);
    lv_obj_set_width(ui_LeftTranscribeText1, lv_pct(100));
    lv_obj_set_height(ui_LeftTranscribeText1, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_LeftTranscribeText1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LeftTranscribeText1,
                      "Text dsad asd asd sa asd as dsad  qwwq we rwqr we rwer ewr wq rewq ewq rwq rwq rqwe rwqe r");
    lv_obj_set_style_text_align(ui_LeftTranscribeText1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LeftTranscribeText1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LeftTranscribeText1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LeftTranscribeText1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LeftTranscribeText1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RightPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_RightPanel, 425);
    lv_obj_set_height(ui_RightPanel, 376);
    lv_obj_set_x(ui_RightPanel, 221);
    lv_obj_set_y(ui_RightPanel, -3);
    lv_obj_set_align(ui_RightPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RightPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_RightPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_RightTranscribe = lv_obj_create(ui_RightPanel);
    lv_obj_set_width(ui_RightTranscribe, lv_pct(100));
    lv_obj_set_height(ui_RightTranscribe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RightTranscribe, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RightTranscribe, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_pad_left(ui_RightTranscribe, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RightTranscribe, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RightTranscribe, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RightTranscribe, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_RightTranscribeBubble = lv_obj_create(ui_RightTranscribe);
    lv_obj_set_width(ui_RightTranscribeBubble, lv_pct(80));
    lv_obj_set_height(ui_RightTranscribeBubble, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RightTranscribeBubble, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_RightTranscribeBubble, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RightTranscribeBubble, lv_color_hex(0x64BDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RightTranscribeBubble, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_RightTranscribeBubble, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RightTranscribeBubble, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RightTranscribeBubble, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RightTranscribeBubble, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_RightTranscribeText = lv_label_create(ui_RightTranscribeBubble);
    lv_obj_set_width(ui_RightTranscribeText, lv_pct(100));
    lv_obj_set_height(ui_RightTranscribeText, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_RightTranscribeText, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_RightTranscribeText,
                      "Text dsad asd asd sa asd as dsad  qwwq we rwqr we rwer ewr wq rewq ewq rwq rwq rqwe rwqe r");
    lv_obj_set_style_text_align(ui_RightTranscribeText, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_RightTranscribeText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RightTranscribeText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RightTranscribeText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RightTranscribeText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RightTranslate = lv_obj_create(ui_RightPanel);
    lv_obj_set_width(ui_RightTranslate, lv_pct(100));
    lv_obj_set_height(ui_RightTranslate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RightTranslate, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RightTranslate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_pad_left(ui_RightTranslate, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RightTranslate, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RightTranslate, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RightTranslate, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_RightTranslateBubble = lv_obj_create(ui_RightTranslate);
    lv_obj_set_width(ui_RightTranslateBubble, lv_pct(80));
    lv_obj_set_height(ui_RightTranslateBubble, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RightTranslateBubble, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_RightTranslateBubble, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RightTranslateBubble, lv_color_hex(0x78868B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RightTranslateBubble, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_RightTranslateBubble, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RightTranslateBubble, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RightTranslateBubble, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RightTranslateBubble, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_RightTranslateText = lv_label_create(ui_RightTranslateBubble);
    lv_obj_set_width(ui_RightTranslateText, lv_pct(100));
    lv_obj_set_height(ui_RightTranslateText, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_RightTranslateText, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_RightTranslateText,
                      "Text dsad asd asd sa asd as dsad  qwwq we rwqr we rwer ewr wq rewq ewq rwq rwq rqwe rwqe r");
    lv_obj_set_style_text_align(ui_RightTranslateText, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_RightTranslateText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RightTranslateText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RightTranslateText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RightTranslateText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RightTranscribe1 = lv_obj_create(ui_RightPanel);
    lv_obj_set_width(ui_RightTranscribe1, lv_pct(100));
    lv_obj_set_height(ui_RightTranscribe1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RightTranscribe1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RightTranscribe1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_pad_left(ui_RightTranscribe1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RightTranscribe1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RightTranscribe1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RightTranscribe1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_RightTranscribeBubble1 = lv_obj_create(ui_RightTranscribe1);
    lv_obj_set_width(ui_RightTranscribeBubble1, lv_pct(80));
    lv_obj_set_height(ui_RightTranscribeBubble1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RightTranscribeBubble1, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_RightTranscribeBubble1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RightTranscribeBubble1, lv_color_hex(0x64BDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RightTranscribeBubble1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_RightTranscribeBubble1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RightTranscribeBubble1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RightTranscribeBubble1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RightTranscribeBubble1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_RightTranscribeText1 = lv_label_create(ui_RightTranscribeBubble1);
    lv_obj_set_width(ui_RightTranscribeText1, lv_pct(100));
    lv_obj_set_height(ui_RightTranscribeText1, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_RightTranscribeText1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_RightTranscribeText1,
                      "Text dsad asd asd sa asd as dsad  qwwq we rwqr we rwer ewr wq rewq ewq rwq rwq rqwe rwqe r");
    lv_obj_set_style_text_align(ui_RightTranscribeText1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_RightTranscribeText1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RightTranscribeText1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RightTranscribeText1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RightTranscribeText1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

}
