// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Start_Screen_screen_init(void)
{
    ui_Start_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Start_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Start_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Start_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_User_1 = lv_obj_create(ui_Start_Screen);
    lv_obj_set_width(ui_Panel_User_1, 462);
    lv_obj_set_height(ui_Panel_User_1, 354);
    lv_obj_set_x(ui_Panel_User_1, 0);
    lv_obj_set_y(ui_Panel_User_1, 212);
    lv_obj_set_align(ui_Panel_User_1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_User_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Panel_User_1, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_Panel_User_1, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_Panel_User_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_User_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_User_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_User_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Panel_User_1, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_User_1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_English_Button = lv_btn_create(ui_Panel_User_1);
    lv_obj_set_width(ui_English_Button, 116);
    lv_obj_set_height(ui_English_Button, 32);
    lv_obj_set_x(ui_English_Button, 0);
    lv_obj_set_y(ui_English_Button, -137);
    lv_obj_set_align(ui_English_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_English_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_English_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_English_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_English_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_English_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_English_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_English_Button, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_English_Button, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_English_Button);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "English");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Noto_Sans_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chinese_Button = lv_btn_create(ui_Panel_User_1);
    lv_obj_set_width(ui_Chinese_Button, 116);
    lv_obj_set_height(ui_Chinese_Button, 32);
    lv_obj_set_x(ui_Chinese_Button, 0);
    lv_obj_set_y(ui_Chinese_Button, -98);
    lv_obj_set_align(ui_Chinese_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chinese_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Chinese_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Chinese_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chinese_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Chinese_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Chinese_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Chinese_Button, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Chinese_Button, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Chinese_Button);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "简体中文");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Noto_Sans_Regular_SC, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thai_Button = lv_btn_create(ui_Panel_User_1);
    lv_obj_set_width(ui_Thai_Button, 116);
    lv_obj_set_height(ui_Thai_Button, 32);
    lv_obj_set_x(ui_Thai_Button, 0);
    lv_obj_set_y(ui_Thai_Button, 59);
    lv_obj_set_align(ui_Thai_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Thai_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Thai_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Thai_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Thai_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Thai_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Thai_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Thai_Button, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thai_Button, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Thai_Button);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "ไทย");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Noto_Sans_Regular_Thai_Looped, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bahasa_Melayu_Button = lv_btn_create(ui_Panel_User_1);
    lv_obj_set_width(ui_Bahasa_Melayu_Button, 124);
    lv_obj_set_height(ui_Bahasa_Melayu_Button, 32);
    lv_obj_set_x(ui_Bahasa_Melayu_Button, 0);
    lv_obj_set_y(ui_Bahasa_Melayu_Button, -59);
    lv_obj_set_align(ui_Bahasa_Melayu_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bahasa_Melayu_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Bahasa_Melayu_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Bahasa_Melayu_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bahasa_Melayu_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Bahasa_Melayu_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Bahasa_Melayu_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Bahasa_Melayu_Button, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Bahasa_Melayu_Button, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Bahasa_Melayu_Button);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Bahasa Melayu");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Noto_Sans_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bahasa_Indonesia_Button = lv_btn_create(ui_Panel_User_1);
    lv_obj_set_width(ui_Bahasa_Indonesia_Button, 155);
    lv_obj_set_height(ui_Bahasa_Indonesia_Button, 32);
    lv_obj_set_x(ui_Bahasa_Indonesia_Button, 0);
    lv_obj_set_y(ui_Bahasa_Indonesia_Button, -19);
    lv_obj_set_align(ui_Bahasa_Indonesia_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bahasa_Indonesia_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Bahasa_Indonesia_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Bahasa_Indonesia_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bahasa_Indonesia_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Bahasa_Indonesia_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Bahasa_Indonesia_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Bahasa_Indonesia_Button, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Bahasa_Indonesia_Button, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Bahasa_Indonesia_Button);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Bahasa Indonesia");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_Noto_Sans_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Vietnamese_Button = lv_btn_create(ui_Panel_User_1);
    lv_obj_set_width(ui_Vietnamese_Button, 116);
    lv_obj_set_height(ui_Vietnamese_Button, 32);
    lv_obj_set_x(ui_Vietnamese_Button, 0);
    lv_obj_set_y(ui_Vietnamese_Button, 98);
    lv_obj_set_align(ui_Vietnamese_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Vietnamese_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Vietnamese_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Vietnamese_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Vietnamese_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Vietnamese_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Vietnamese_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Vietnamese_Button, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Vietnamese_Button, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Vietnamese_Button);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Tiếng Việt");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Noto_Sans_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Hindi_Button = lv_btn_create(ui_Panel_User_1);
    lv_obj_set_width(ui_Hindi_Button, 116);
    lv_obj_set_height(ui_Hindi_Button, 32);
    lv_obj_set_x(ui_Hindi_Button, 0);
    lv_obj_set_y(ui_Hindi_Button, 19);
    lv_obj_set_align(ui_Hindi_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Hindi_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Hindi_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Hindi_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Hindi_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Hindi_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Hindi_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Hindi_Button, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Hindi_Button, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Hindi_Button);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "हिन्दी");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_Noto_Sans_Regular_Devanagari, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Filipino_Button = lv_btn_create(ui_Panel_User_1);
    lv_obj_set_width(ui_Filipino_Button, 116);
    lv_obj_set_height(ui_Filipino_Button, 32);
    lv_obj_set_x(ui_Filipino_Button, 0);
    lv_obj_set_y(ui_Filipino_Button, 137);
    lv_obj_set_align(ui_Filipino_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Filipino_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Filipino_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Filipino_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Filipino_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Filipino_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Filipino_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Filipino_Button, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Filipino_Button, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Filipino_Button);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Filipino");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_Noto_Sans_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spacer_Bar_White = lv_obj_create(ui_Start_Screen);
    lv_obj_set_width(ui_Spacer_Bar_White, 480);
    lv_obj_set_height(ui_Spacer_Bar_White, 48);
    lv_obj_set_align(ui_Spacer_Bar_White, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spacer_Bar_White, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Spacer_Bar_White, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Optional_Text = lv_label_create(ui_Spacer_Bar_White);
    lv_obj_set_width(ui_Optional_Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Optional_Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Optional_Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Optional_Text, "Select Language");
    lv_obj_add_flag(ui_Optional_Text, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Optional_Text, lv_color_hex(0x144A82), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Optional_Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Optional_Text, &ui_font_Noto_Sans_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_User_2 = lv_obj_create(ui_Start_Screen);
    lv_obj_set_width(ui_Panel_User_2, 462);
    lv_obj_set_height(ui_Panel_User_2, 354);
    lv_obj_set_x(ui_Panel_User_2, 462);
    lv_obj_set_y(ui_Panel_User_2, 142);
    lv_obj_set_align(ui_Panel_User_2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_User_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Panel_User_2, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_Panel_User_2, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_Panel_User_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_User_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_User_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_User_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Panel_User_2, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Panel_User_2, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_User_2, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_English_Button1 = lv_btn_create(ui_Panel_User_2);
    lv_obj_set_width(ui_English_Button1, 116);
    lv_obj_set_height(ui_English_Button1, 32);
    lv_obj_set_x(ui_English_Button1, 0);
    lv_obj_set_y(ui_English_Button1, -137);
    lv_obj_set_align(ui_English_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_English_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_English_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_English_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_English_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_English_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_English_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_English_Button1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_English_Button1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_English_Button1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "English");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Noto_Sans_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chinese_Button1 = lv_btn_create(ui_Panel_User_2);
    lv_obj_set_width(ui_Chinese_Button1, 116);
    lv_obj_set_height(ui_Chinese_Button1, 32);
    lv_obj_set_x(ui_Chinese_Button1, 0);
    lv_obj_set_y(ui_Chinese_Button1, -98);
    lv_obj_set_align(ui_Chinese_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chinese_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Chinese_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Chinese_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chinese_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Chinese_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Chinese_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Chinese_Button1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Chinese_Button1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Chinese_Button1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "简体中文");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Noto_Sans_Regular_SC, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thai_Button1 = lv_btn_create(ui_Panel_User_2);
    lv_obj_set_width(ui_Thai_Button1, 116);
    lv_obj_set_height(ui_Thai_Button1, 32);
    lv_obj_set_x(ui_Thai_Button1, 0);
    lv_obj_set_y(ui_Thai_Button1, 59);
    lv_obj_set_align(ui_Thai_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Thai_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Thai_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Thai_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Thai_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Thai_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Thai_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Thai_Button1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thai_Button1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Thai_Button1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "ไทย");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_Noto_Sans_Regular_Thai_Looped, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bahasa_Melayu_Button1 = lv_btn_create(ui_Panel_User_2);
    lv_obj_set_width(ui_Bahasa_Melayu_Button1, 124);
    lv_obj_set_height(ui_Bahasa_Melayu_Button1, 32);
    lv_obj_set_x(ui_Bahasa_Melayu_Button1, 0);
    lv_obj_set_y(ui_Bahasa_Melayu_Button1, -59);
    lv_obj_set_align(ui_Bahasa_Melayu_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bahasa_Melayu_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Bahasa_Melayu_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Bahasa_Melayu_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bahasa_Melayu_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Bahasa_Melayu_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Bahasa_Melayu_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Bahasa_Melayu_Button1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Bahasa_Melayu_Button1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Bahasa_Melayu_Button1);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Bahasa Melayu");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_Noto_Sans_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bahasa_Indonesia_Button1 = lv_btn_create(ui_Panel_User_2);
    lv_obj_set_width(ui_Bahasa_Indonesia_Button1, 155);
    lv_obj_set_height(ui_Bahasa_Indonesia_Button1, 32);
    lv_obj_set_x(ui_Bahasa_Indonesia_Button1, 0);
    lv_obj_set_y(ui_Bahasa_Indonesia_Button1, -19);
    lv_obj_set_align(ui_Bahasa_Indonesia_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bahasa_Indonesia_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Bahasa_Indonesia_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Bahasa_Indonesia_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bahasa_Indonesia_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Bahasa_Indonesia_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Bahasa_Indonesia_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Bahasa_Indonesia_Button1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Bahasa_Indonesia_Button1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Bahasa_Indonesia_Button1);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Bahasa Indonesia");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_Noto_Sans_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Vietnamese_Button1 = lv_btn_create(ui_Panel_User_2);
    lv_obj_set_width(ui_Vietnamese_Button1, 116);
    lv_obj_set_height(ui_Vietnamese_Button1, 32);
    lv_obj_set_x(ui_Vietnamese_Button1, 0);
    lv_obj_set_y(ui_Vietnamese_Button1, 98);
    lv_obj_set_align(ui_Vietnamese_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Vietnamese_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Vietnamese_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Vietnamese_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Vietnamese_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Vietnamese_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Vietnamese_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Vietnamese_Button1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Vietnamese_Button1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Vietnamese_Button1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Tiếng Việt");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_Noto_Sans_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Hindi_Button1 = lv_btn_create(ui_Panel_User_2);
    lv_obj_set_width(ui_Hindi_Button1, 116);
    lv_obj_set_height(ui_Hindi_Button1, 32);
    lv_obj_set_x(ui_Hindi_Button1, 0);
    lv_obj_set_y(ui_Hindi_Button1, 19);
    lv_obj_set_align(ui_Hindi_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Hindi_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Hindi_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Hindi_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Hindi_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Hindi_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Hindi_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Hindi_Button1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Hindi_Button1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Hindi_Button1);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "हिन्दी");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_Noto_Sans_Regular_Devanagari, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Filipino_Button1 = lv_btn_create(ui_Panel_User_2);
    lv_obj_set_width(ui_Filipino_Button1, 116);
    lv_obj_set_height(ui_Filipino_Button1, 32);
    lv_obj_set_x(ui_Filipino_Button1, 0);
    lv_obj_set_y(ui_Filipino_Button1, 137);
    lv_obj_set_align(ui_Filipino_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Filipino_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Filipino_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Filipino_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Filipino_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Filipino_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Filipino_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Filipino_Button1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Filipino_Button1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Filipino_Button1);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Filipino");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_Noto_Sans_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

}
