// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Translation_Screen_screen_init(void)
{
    ui_Translation_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Translation_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Translation_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Translation_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dialogue_User_1 = lv_obj_create(ui_Translation_Screen);
    lv_obj_set_width(ui_Dialogue_User_1, 462);
    lv_obj_set_height(ui_Dialogue_User_1, 354);
    lv_obj_set_x(ui_Dialogue_User_1, 0);
    lv_obj_set_y(ui_Dialogue_User_1, 212);
    lv_obj_set_align(ui_Dialogue_User_1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Dialogue_User_1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Dialogue_User_1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scrollbar_mode(ui_Dialogue_User_1, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_Dialogue_User_1, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_Dialogue_User_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dialogue_User_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Dialogue_User_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Dialogue_User_1, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dialogue_User_1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Type_C_Panel_2 = lv_obj_create(ui_Dialogue_User_1);
    lv_obj_set_width(ui_Type_C_Panel_2, lv_pct(100));
    lv_obj_set_height(ui_Type_C_Panel_2, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_Type_C_Panel_2, -105);
    lv_obj_set_y(ui_Type_C_Panel_2, -43);
    lv_obj_set_align(ui_Type_C_Panel_2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Type_C_Panel_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Type_C_Panel_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Type_C_Panel_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Type_C_Panel_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Type_C_Panel_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_C_Panel_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_C_Panel_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_C_Panel_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Type_C_Panel_2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_C_Panel_2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_C_Panel_2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_C_Panel_2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Type_C_Bubble_2 = lv_obj_create(ui_Type_C_Panel_2);
    lv_obj_set_width(ui_Type_C_Bubble_2, lv_pct(80));
    lv_obj_set_height(ui_Type_C_Bubble_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Type_C_Bubble_2, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Type_C_Bubble_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Type_C_Bubble_2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Type_C_Bubble_2, lv_color_hex(0x26252A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Type_C_Bubble_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Type_C_Bubble_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Type_C_Bubble_2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_C_Bubble_2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_C_Bubble_2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_C_Bubble_2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Type_C_Text_2 = lv_label_create(ui_Type_C_Bubble_2);
    lv_obj_set_width(ui_Type_C_Text_2, lv_pct(100));
    lv_obj_set_height(ui_Type_C_Text_2, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Type_C_Text_2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Type_C_Text_2, "Hello.");
    lv_obj_set_style_text_color(ui_Type_C_Text_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Type_C_Text_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Type_C_Text_2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Type_C_Text_2, &ui_font_Noto_Sans_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Type_C_Text_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_C_Text_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_C_Text_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_C_Text_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Type_C_Panel = lv_obj_create(ui_Dialogue_User_1);
    lv_obj_set_width(ui_Type_C_Panel, lv_pct(100));
    lv_obj_set_height(ui_Type_C_Panel, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_Type_C_Panel, -105);
    lv_obj_set_y(ui_Type_C_Panel, -43);
    lv_obj_set_align(ui_Type_C_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Type_C_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Type_C_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Type_C_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Type_C_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Type_C_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_C_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_C_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_C_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Type_C_Panel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_C_Panel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_C_Panel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_C_Panel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Type_C_Bubble = lv_obj_create(ui_Type_C_Panel);
    lv_obj_set_width(ui_Type_C_Bubble, lv_pct(80));
    lv_obj_set_height(ui_Type_C_Bubble, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_align(ui_Type_C_Bubble, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Type_C_Bubble, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Type_C_Bubble, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Type_C_Bubble, lv_color_hex(0x26252A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Type_C_Bubble, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Type_C_Bubble, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Type_C_Bubble, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_C_Bubble, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_C_Bubble, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_C_Bubble, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Type_C_Text = lv_label_create(ui_Type_C_Bubble);
    lv_obj_set_width(ui_Type_C_Text, lv_pct(100));
    lv_obj_set_height(ui_Type_C_Text, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_align(ui_Type_C_Text, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Type_C_Text, "Could you direct me to the nearest bus stop please?");
    lv_obj_set_style_text_color(ui_Type_C_Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Type_C_Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Type_C_Text, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Type_C_Text, &ui_font_Noto_Sans_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Type_C_Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_C_Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_C_Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_C_Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Type_A_Panel = lv_obj_create(ui_Dialogue_User_1);
    lv_obj_set_width(ui_Type_A_Panel, lv_pct(100));
    lv_obj_set_height(ui_Type_A_Panel, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_align(ui_Type_A_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Type_A_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Type_A_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Type_A_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Type_A_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Type_A_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_A_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_A_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_A_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Type_A_Panel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_A_Panel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_A_Panel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_A_Panel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Type_A_Bubble = lv_obj_create(ui_Type_A_Panel);
    lv_obj_set_width(ui_Type_A_Bubble, lv_pct(80));
    lv_obj_set_height(ui_Type_A_Bubble, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_align(ui_Type_A_Bubble, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Type_A_Bubble, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Type_A_Bubble, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Type_A_Bubble, lv_color_hex(0x144A82), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Type_A_Bubble, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Type_A_Bubble, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Type_A_Text = lv_label_create(ui_Type_A_Bubble);
    lv_obj_set_width(ui_Type_A_Text, lv_pct(100));
    lv_obj_set_height(ui_Type_A_Text, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_align(ui_Type_A_Text, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Type_A_Text, "Sure, it is right across the street.");
    lv_obj_set_style_text_color(ui_Type_A_Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Type_A_Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Type_A_Text, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Type_A_Text, &ui_font_Noto_Sans_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Type_A_Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_A_Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_A_Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_A_Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Type_B_Panel = lv_obj_create(ui_Dialogue_User_1);
    lv_obj_set_width(ui_Type_B_Panel, lv_pct(100));
    lv_obj_set_height(ui_Type_B_Panel, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_align(ui_Type_B_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Type_B_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Type_B_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Type_B_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Type_B_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Type_B_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_B_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_B_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_B_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Type_B_Panel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_B_Panel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_B_Panel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_B_Panel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Type_B_Bubble = lv_obj_create(ui_Type_B_Panel);
    lv_obj_set_width(ui_Type_B_Bubble, lv_pct(80));
    lv_obj_set_height(ui_Type_B_Bubble, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_align(ui_Type_B_Bubble, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Type_B_Bubble, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Type_B_Bubble, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Type_B_Bubble, lv_color_hex(0x082340), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Type_B_Bubble, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Type_B_Bubble, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Type_B_Bubble, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Type_B_Bubble, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Type_B_Text = lv_label_create(ui_Type_B_Bubble);
    lv_obj_set_width(ui_Type_B_Text, lv_pct(100));
    lv_obj_set_height(ui_Type_B_Text, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_align(ui_Type_B_Text, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Type_B_Text, "I can guide you th..");
    lv_label_set_recolor(ui_Type_B_Text, "true");
    lv_obj_set_style_text_color(ui_Type_B_Text, lv_color_hex(0x737373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Type_B_Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Type_B_Text, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Type_B_Text, &ui_font_Noto_Sans_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Type_B_Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_B_Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_B_Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_B_Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Status_Panel = lv_obj_create(ui_Translation_Screen);
    lv_obj_set_width(ui_Status_Panel, 480);
    lv_obj_set_height(ui_Status_Panel, 48);
    lv_obj_set_align(ui_Status_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Status_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Status_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Icon_Mic = lv_img_create(ui_Status_Panel);
    lv_img_set_src(ui_Icon_Mic, &ui_img_mic_icon_png);
    lv_obj_set_width(ui_Icon_Mic, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Icon_Mic, LV_SIZE_CONTENT);    /// 495
    lv_obj_set_align(ui_Icon_Mic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Icon_Mic, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Icon_Mic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Icon_Mic, 20);

    ui_Icon_Mic_Inactive = lv_img_create(ui_Status_Panel);
    lv_img_set_src(ui_Icon_Mic_Inactive, &ui_img_mic_icon_inactive_png);
    lv_obj_set_width(ui_Icon_Mic_Inactive, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Icon_Mic_Inactive, LV_SIZE_CONTENT);    /// 495
    lv_obj_set_align(ui_Icon_Mic_Inactive, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Icon_Mic_Inactive, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Icon_Mic_Inactive, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Icon_Mic_Inactive, 35);

    ui_Icon_Mic_Active = lv_img_create(ui_Status_Panel);
    lv_img_set_src(ui_Icon_Mic_Active, &ui_img_mic_icon_active_png);
    lv_obj_set_width(ui_Icon_Mic_Active, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Icon_Mic_Active, LV_SIZE_CONTENT);    /// 495
    lv_obj_set_align(ui_Icon_Mic_Active, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Icon_Mic_Active, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Icon_Mic_Active, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Icon_Mic_Active, 35);

    ui_Dialogue_User_2 = lv_obj_create(ui_Translation_Screen);
    lv_obj_set_width(ui_Dialogue_User_2, 462);
    lv_obj_set_height(ui_Dialogue_User_2, 354);
    lv_obj_set_x(ui_Dialogue_User_2, 462);
    lv_obj_set_y(ui_Dialogue_User_2, 142);
    lv_obj_set_align(ui_Dialogue_User_2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Dialogue_User_2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Dialogue_User_2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scrollbar_mode(ui_Dialogue_User_2, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_Dialogue_User_2, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_Dialogue_User_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dialogue_User_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Dialogue_User_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Dialogue_User_2, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Dialogue_User_2, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dialogue_User_2, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Type_A_Panel_2 = lv_obj_create(ui_Dialogue_User_2);
    lv_obj_set_width(ui_Type_A_Panel_2, lv_pct(100));
    lv_obj_set_height(ui_Type_A_Panel_2, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_align(ui_Type_A_Panel_2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Type_A_Panel_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Type_A_Panel_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Type_A_Panel_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Type_A_Panel_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Type_A_Panel_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_A_Panel_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_A_Panel_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_A_Panel_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Type_A_Panel_2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_A_Panel_2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_A_Panel_2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_A_Panel_2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Type_A_Bubble_2 = lv_obj_create(ui_Type_A_Panel_2);
    lv_obj_set_width(ui_Type_A_Bubble_2, lv_pct(80));
    lv_obj_set_height(ui_Type_A_Bubble_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Type_A_Bubble_2, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Type_A_Bubble_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Type_A_Bubble_2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Type_A_Bubble_2, lv_color_hex(0x144A82), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Type_A_Bubble_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Type_A_Bubble_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Type_A_Bubble_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Type_A_Bubble_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Type_A_Text_2 = lv_label_create(ui_Type_A_Bubble_2);
    lv_obj_set_width(ui_Type_A_Text_2, lv_pct(100));
    lv_obj_set_height(ui_Type_A_Text_2, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Type_A_Text_2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Type_A_Text_2, "你好。");
    lv_obj_set_style_text_color(ui_Type_A_Text_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Type_A_Text_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Type_A_Text_2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Type_A_Text_2, &ui_font_Noto_Sans_Regular_SC, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Type_A_Text_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_A_Text_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_A_Text_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_A_Text_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Type_A_Panel_3 = lv_obj_create(ui_Dialogue_User_2);
    lv_obj_set_width(ui_Type_A_Panel_3, lv_pct(100));
    lv_obj_set_height(ui_Type_A_Panel_3, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_align(ui_Type_A_Panel_3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Type_A_Panel_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Type_A_Panel_3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Type_A_Panel_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Type_A_Panel_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Type_A_Panel_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_A_Panel_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_A_Panel_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_A_Panel_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Type_A_Panel_3, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_A_Panel_3, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_A_Panel_3, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_A_Panel_3, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Type_A_Bubble_3 = lv_obj_create(ui_Type_A_Panel_3);
    lv_obj_set_width(ui_Type_A_Bubble_3, lv_pct(80));
    lv_obj_set_height(ui_Type_A_Bubble_3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Type_A_Bubble_3, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Type_A_Bubble_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Type_A_Bubble_3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Type_A_Bubble_3, lv_color_hex(0x144A82), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Type_A_Bubble_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Type_A_Bubble_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Type_A_Bubble_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Type_A_Bubble_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Type_A_Text_3 = lv_label_create(ui_Type_A_Bubble_3);
    lv_obj_set_width(ui_Type_A_Text_3, lv_pct(100));
    lv_obj_set_height(ui_Type_A_Text_3, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Type_A_Text_3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Type_A_Text_3, "请问巴士站在哪里？");
    lv_obj_set_style_text_color(ui_Type_A_Text_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Type_A_Text_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Type_A_Text_3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Type_A_Text_3, &ui_font_Noto_Sans_Regular_SC, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Type_A_Text_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_A_Text_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_A_Text_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_A_Text_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Type_C_Panel_3 = lv_obj_create(ui_Dialogue_User_2);
    lv_obj_set_width(ui_Type_C_Panel_3, lv_pct(100));
    lv_obj_set_height(ui_Type_C_Panel_3, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_Type_C_Panel_3, -105);
    lv_obj_set_y(ui_Type_C_Panel_3, -43);
    lv_obj_set_align(ui_Type_C_Panel_3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Type_C_Panel_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Type_C_Panel_3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Type_C_Panel_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Type_C_Panel_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Type_C_Panel_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_C_Panel_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_C_Panel_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_C_Panel_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Type_C_Panel_3, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_C_Panel_3, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_C_Panel_3, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_C_Panel_3, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Type_C_Bubble_3 = lv_obj_create(ui_Type_C_Panel_3);
    lv_obj_set_width(ui_Type_C_Bubble_3, lv_pct(80));
    lv_obj_set_height(ui_Type_C_Bubble_3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Type_C_Bubble_3, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Type_C_Bubble_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Type_C_Bubble_3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Type_C_Bubble_3, lv_color_hex(0x26252A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Type_C_Bubble_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Type_C_Bubble_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Type_C_Bubble_3, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_C_Bubble_3, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_C_Bubble_3, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_C_Bubble_3, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Type_C_Text_3 = lv_label_create(ui_Type_C_Bubble_3);
    lv_obj_set_width(ui_Type_C_Text_3, lv_pct(100));
    lv_obj_set_height(ui_Type_C_Text_3, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Type_C_Text_3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Type_C_Text_3, "当然，就在马路对面。");
    lv_obj_set_style_text_color(ui_Type_C_Text_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Type_C_Text_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Type_C_Text_3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Type_C_Text_3, &ui_font_Noto_Sans_Regular_SC, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Type_C_Text_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_C_Text_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_C_Text_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_C_Text_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Type_D_Panel = lv_obj_create(ui_Dialogue_User_2);
    lv_obj_set_width(ui_Type_D_Panel, lv_pct(100));
    lv_obj_set_height(ui_Type_D_Panel, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_Type_D_Panel, -105);
    lv_obj_set_y(ui_Type_D_Panel, -43);
    lv_obj_set_align(ui_Type_D_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Type_D_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Type_D_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Type_D_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Type_D_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Type_D_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_D_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_D_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_D_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Type_D_Panel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_D_Panel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_D_Panel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_D_Panel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Type_D_Bubble = lv_obj_create(ui_Type_D_Panel);
    lv_obj_set_width(ui_Type_D_Bubble, lv_pct(80));
    lv_obj_set_height(ui_Type_D_Bubble, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_align(ui_Type_D_Bubble, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Type_D_Bubble, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Type_D_Bubble, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Type_D_Bubble, lv_color_hex(0x26252A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Type_D_Bubble, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Type_D_Bubble, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Type_D_Bubble, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_D_Bubble, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_D_Bubble, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_D_Bubble, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Type_D_Text = lv_label_create(ui_Type_D_Bubble);
    lv_obj_set_width(ui_Type_D_Text, lv_pct(100));
    lv_obj_set_height(ui_Type_D_Text, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_align(ui_Type_D_Text, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Type_D_Text, "我可以带你去那。。。");
    lv_obj_set_style_text_color(ui_Type_D_Text, lv_color_hex(0x898989), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Type_D_Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Type_D_Text, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Type_D_Text, &ui_font_Noto_Sans_Regular_SC, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Type_D_Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Type_D_Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Type_D_Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Type_D_Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

}
